### ISSUE TITLE
Thread Safety Part #2

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-consortium/tesseract#35]
I'm not sure that all of the threading issues are gone. I absolutely do not discount that the error could be in my code (or likely is), but I wanted to post this notice.

While running some tests with a modified version of Descartes, I noticed that the plans I got back were inconsistent. About 1 in 5 plans returned a slightly different result. Disabling threading seems to fix this. Comparing the plans, it does appear that the collision checker is returning a different number of states every once in a while.

Furthermore, on much rarer occassions I get segfaults. After trying my program a hundred times in GDB, I finally caught this back-trace. Does this ring any bells? The `threadIndex` variable mentioned on the line it died at makes me suspicious...

```
0x00007fffdd79f57f in CProfileManager::Start_Profile (name=0x7fffdd564b88 "btCompoundCompoundLeafCallback::Process") at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_ext/bullet3_ros/bullet3/src/LinearMath/btQuickprof.cpp:555
555		if (name != gCurrentNodes[threadIndex]->Get_Name()) {
(gdb) bt
#0  0x00007fffdd79f57f in CProfileManager::Start_Profile (name=0x7fffdd564b88 "btCompoundCompoundLeafCallback::Process") at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_ext/bullet3_ros/bullet3/src/LinearMath/btQuickprof.cpp:555
#1  0x00007fffdd4dd251 in btCompoundCompoundLeafCallback::Process (this=this@entry=0x7fff61cf50f0, leaf0=leaf0@entry=0x9e8dd0, leaf1=leaf1@entry=0xa048f0)
    at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_ext/bullet3_ros/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp:130
#2  0x00007fffdd4dd0e0 in MycollideTT (distanceThreshold=0, callback=0x7fff61cf50f0, xform=<synthetic pointer>, root1=<optimized out>, root0=<optimized out>)
    at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_ext/bullet3_ros/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp:296
#3  btCompoundCompoundCollisionAlgorithm::processCollision (this=0xb1c7900, body0Wrap=0x7fff61cf6a10, body1Wrap=0x7fff61cf6a40, dispatchInfo=..., resultOut=0x7fff61cf6a70)
    at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_ext/bullet3_ros/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp:371
#4  0x00007fffdd9c834d in tesseract::tesseract_bullet::TesseractCollisionPairCallback::processOverlap (this=0x7fff61cf6b90, pair=...)
    at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h:681
#5  0x00007fffdd4ab3d0 in btHashedOverlappingPairCache::processAllOverlappingPairs (this=0xb28bf00, callback=0x7fff61cf6b90, dispatcher=0xb286c50)
    at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_ext/bullet3_ros/bullet3/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp:386
#6  0x00007fffdd9cd838 in tesseract::tesseract_bullet::BulletDiscreteBVHManager::contactTest (this=0xb1c6850, collisions=...) at /home/jon/ros/trajopt_ws/src/tess_stuff/tesseract/tesseract_collision/src/bullet/bullet_discrete_managers.cpp:491
#7  0x00007ffff2d864d4 in descartes_light::TesseractCollision::validate (this=0xb1c60a0, pos=0x7fff380106e0, size=<optimized out>) at /home/jon/ros/trajopt_ws/src/tess_stuff/descartes_light/src/descartes_light/collision_checker.cpp:38
```

**Comment by Levi-Armstrong** [comment]
This has been addressed by a few PR on that add the ability to get a StateSolver.
